language: node_js

sudo: required

node_js: 8

branches:
  only:
    - master

before_install:
  - echo "Hexo environment pre install start."
  - export  TZ='Asia/Shanghai'

install:
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save
  - npm install -g gulp@3.9.1
  - echo "hexo and packages install complete."

before_script:
  - sed -i "s~url: http://vactech.gitee.io~url: http://vactech.github.io~" _config.yml
  - sed -i "s~server_link: https://gitee.com~server_link: https://github.com~" theme/Wikitten/_config.yml
  - sed -i "s~repertory: vactech~repertory: vactech.github.io~" theme/Wikitten/_config.yml
  - sed -i "s~branch: hexo/wiki~branch: Wikitten~" theme/Wikitten/_config.yml
  - sed -i "s~889e7313e1937fcadec1b944c9dd316a~0847191c64787500a81863beb4803445~" themes/Wikitten/_config.yml

script:
  - hexo clean
  - hexo generate

after_success:
  - gulp
  - git config user.name "${GIT_VAC_NAME}"
  - git config user.email "${GIT_VAC_EMAIL}"
  - sed -i "s~git@gitee.com:~https://${GIT_VAC_TOKEN}@github.com/~" _config.yml
  - sed -i "s~vactech/vactech.git~vactech/vactech.github.io.git~" _config.yml
  - hexo deploy

notifications:
  email: true
