# Travis CI Tutorial
# https://docs.travis-ci.com/user/tutorial/
# The job lifecycle 
# https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

language: node_js   # 指定语言环境
sudo: required      # 是否需要 sudo 权限
node_js:            # 指定 NodeJS 版本
  - 8

#cache:
#  directories:
#    - node_modules

branches:   # 指定要构建的分支
  only:     # only 表示只构建以下分支
    - master

# S: Build Lifecycle

before_install:
  - echo "Hexo environment pre install start."
  - export TZ='Asia/Shanghai'   # 解决 Travis CI commit comments 的时差问题

install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install -g hexo-cli
  - npm install
  - npm install hexo-deployer-git --save
  - npm install -g gulp@3.9.1                   # 指定安装 gulp 3.9.1 版本
  - echo "hexo and packages install complete."

script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - source travis_before_script.sh
  - hexo clean
  - hexo generate # Hexo 常规命令，执行清理和生成

after_success: # 在构建成功后要运行的命令，构建失败不会执行
  - gulp
  - git config user.name "${GIT_VAC_NAME}"
  - git config user.email "${GIT_VAC_EMAIL}"
  - sed -i "s~git@gitee.com:~https://${GIT_VAC_TOKEN}@github.com/~" _config.yml
  - sed -i "s~vactech/vactech.git~vactech/vactech.github.io.git~" _config.yml
  # 部署到 vactech/vactech.github.io
  - hexo deploy #> /dev/null # 通过 hexo 的 deploy 命令部署博客

# E: Build LifeCycle

notifications: # 设置通知项
  email: true
